# pool:
#   name: Hosted Windows 2019 with VS2019
#   demands: azureps

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'azure-free-trial1'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: -ResourceGroupLocation 'eastus' -ArtifactStagingDirectory 'artifacts' -ResourceGroupName 'ghrunner'
    azurePowerShellVersion: LatestVersion