# pool:
#   name: Hosted Windows 2019 with VS2019
#   demands: azureps

pool:
  vmImage: 'ubuntu-latest'

# I'd like to run this manually
trigger: none

steps:
- script: sed -i "s|_REPLACETOKEN_|$TOKEN|g; s|_REPLACEREPO_|$REPO|g; s|_REPLACEVER_|$RUNNER_VER|g" artifacts/cloud-init.txt
  env:
    # The secret token needs explicit mapping. The others, not, but I am mapping them anyways so it's clear. 
    TOKEN: $(TOKEN)
    REPO: $(REPO)
    RUNNER_VER: $(RUNNER_VER)
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'Free-Trial-1'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: -ResourceGroupLocation 'eastus' -ArtifactStagingDirectory 'artifacts' -ResourceGroupName $(RESOURCEGROUP) -DeploymentName $(Build.BuildNumber)
    azurePowerShellVersion: LatestVersion
