# pool:
#   name: Hosted Windows 2019 with VS2019
#   demands: azureps

pool:
  vmImage: 'ubuntu-latest'

# I'd like to run this manually
trigger: none

steps:
- script: sed -i 's/REPLACETOKEN/$TOKEN/g; s/REPLACEREPO/$REPO/g' artifacts/cloud-init.txt
  env:
    # map the secret token
    TOKEN: $(TOKEN)
    # this is not needed but I am explicitly mapping it
    REPO: $(REPO)
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'azure-free-trial1'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: -ResourceGroupLocation 'eastus' -ArtifactStagingDirectory 'artifacts' -ResourceGroupName 'ghrunner' -DeploymentName $(Build.BuildNumber)
    azurePowerShellVersion: LatestVersion