pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: 'azure-free-trial1'
    ScriptPath: 'Deploy-AzTemplate.ps1'
    ScriptArguments: -ResourceGroupName 'ghrunner' -ResourceGroupLocation 'uksouth'
    azurePowerShellVersion: LatestVersion